<a href="https://colab.research.google.com/github/ShafinBeLike/AIML-Projects/blob/main/AIML_Practical2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def relu(x):
    return np.maximum(0, x)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

input_data= np.array([[0.5,0.2],[0.3,0.7]])
weights=np.array([[0.1,0.2],[0.3,0.4]])
biases=np.array([0.5,0.1])

def single_layer_forward (input_data, weights, biases, actication_func):
  weighted_sum = np.dot(input_data, weights) + biases
  output = actication_func(weighted_sum)
  return output

output_relu=single_layer_forward(input_data, weights, biases, relu)
print("ReLU Output:")
print(output_relu)

output_sigmoid=single_layer_forward(input_data, weights, biases, sigmoid)
print("Sigmoid actication Output:")
print(output_sigmoid)

output_tanh=single_layer_forward(input_data, weights, biases, tanh)
print("Tanh actication Output:")
print(output_tanh)

ReLU Output:
[[0.61 0.28]
 [0.74 0.44]]
Sigmoid actication Output:
[[0.6479408  0.56954622]
 [0.67699586 0.60825903]]
Tanh actication Output:
[[0.5441271  0.27290508]
 [0.62914516 0.41364444]]
